[PM-16126]: Bump shielded wallet to ledger v5 (#732)
* feat: rewrites core wallet to ts

* fix: lint fixes

* [PM-15627] Rewrite sync + tx history

* [PM-15627] Quick update

* [PM-15627] Quick update

* [PM-15627] Quick update

* [PM-15627] Improve schema for appyStage

* [PM-15627] Update field name

* [PM-15627] Refactor

* feat: rewrite wallet core

* fix: update sync

* feat: remove zswap from capabilities package

* feat: update address format package to ledger v5

* feat: update shielded wallet to ledger v5

* fix: support only v5 ledger in indexer client

* fix: update prover client test

* feat: update node client tests

* [PM-15627] Rewrite sync + tx history

* fix: linter issues

* fix: additional fixes

* fix: add hook timeout

* feat: finish integratint ledger v5

* feat: wraps up ledger v5 integration

* fix: add eslint config to prover client

* fix: set public version for e2e tests wallet

* fix: remove scala packages from workspace

* fix: remove tmp dir for generated txs

* feat: adds wallet facade  (#738)

* feat: adds wallet facade and additional updates

* fix: align state with shielded wallet

* fix: remove internal key derivation

* fix: update tests

* fix: temporarily disable eslint

* fix: fixes types

* fix: rename packages

* fix: remove private tag from packages

* fix: remove private tag from abstractions package

* fix: config publish url

* fix: add facade and node client to cd

* fix: revert version for facade and node client

* fix: downgrade versions

* fix: skip tx generating tests due to permissions issue in gha

* fix: increase hook timeout in UnshieldedWallet.test.ts

* fix: adds docker compose dynamic v4

---------

Co-authored-by: Ian Gregson <ian.gregson@shielded.io>

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -29,8 +29,8 @@ jobs:
           cache-dependency-path: 'yarn.lock'
           # This is required for the npm publish step
           token: ${{ env.MIDNIGHT_GH_TOKEN }}
-          registry-url: "https://npm.pkg.github.com"
-          scope: "@midnight-ntwrk"
+          registry-url: 'https://npm.pkg.github.com'
+          scope: '@midnight-ntwrk'
 
       - name: Configure yarn
         run: |
@@ -43,7 +43,7 @@ jobs:
           yarn install --immutable
 
       - name: Build
-        run:  yarn dist --filter '*wallet-sdk-*'
+        run: yarn dist
 
       - name: Publish release
         run: |
@@ -54,3 +54,8 @@ jobs:
           yarn workspace @midnight-ntwrk/wallet-sdk-indexer-client npm publish || echo "Publishing @midnight-ntwrk/wallet-sdk-indexer-client failed"
           yarn workspace @midnight-ntwrk/wallet-sdk-unshielded-state npm publish || echo "Publishing @midnight-ntwrk/wallet-sdk-unshielded-state failed"
           yarn workspace @midnight-ntwrk/wallet-sdk-unshielded-wallet npm publish || echo "Publishing @midnight-ntwrk/wallet-sdk-unshielded-wallet failed"
+          yarn workspace @midnight-ntwrk/wallet-sdk-shielded npm publish || echo "Publishing @midnight-ntwrk/wallet-sdk-shielded failed"
+          yarn workspace @midnight-ntwrk/wallet-sdk-abstractions npm publish || echo "Publishing @midnight-ntwrk/wallet-sdk-abstractions failed"
+          yarn workspace @midnight-ntwrk/wallet-sdk-prover-client npm publish || echo "Publishing @midnight-ntwrk/wallet-sdk-prover-client failed"
+          yarn workspace @midnight-ntwrk/wallet-sdk-facade npm publish || echo "Publishing @midnight-ntwrk/wallet-sdk-facade failed"
+          yarn workspace @midnight-ntwrk/wallet-sdk-node-client npm publish || echo "Publishing @midnight-ntwrk/wallet-sdk-node-client failed"
