[PM-13250] ci: add smoke tests to ci (#579)
* ci: add smoke tests to ci

* fix: test and report descriptions

* fix: check name

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,6 +4,8 @@ env:
   MIDNIGHT_GH_USER: ${{ secrets.GH_USERNAME }} # For sbt to download dependencies from Midnight org
   MIDNIGHT_GH_TOKEN: ${{ secrets.MIDNIGHTBOT_PACKAGES_WRITE }} # For sbt to download dependencies from Midnight org
   NODE_AUTH_TOKEN: ${{ secrets.MIDNIGHTBOT_PACKAGES_WRITE }}
+  NETWORK: undeployed
+  DEPLOYMENT: local
 
 on:
   pull_request:
@@ -61,9 +63,44 @@ jobs:
             **/target/test-reports/TEST-*.xml
             !examples/node_modules/@midnight-ntwrk/wallet/target/test-reports/TEST-*.xml
 
-      - name: Upload Scala coverage report
-        uses: actions/upload-artifact@v4
+      # scoverage disabled 
+      # - name: Upload Scala coverage report
+      #   uses: actions/upload-artifact@v4
+      #   if: success() || failure()
+      #   with:
+      #     name: scoverage-report
+      #     path: target/scala-3.4.2/scoverage-report
+
+      - name: Run smoke e2e tests
+        run: |
+          yarn dlx turbo test-e2e -- smoke.test.ts
+  
+      - name: Create allure properties
+        if: success() || failure()
+        working-directory: ./typescript/packages/e2e-tests/allure-results
+        run: |
+          echo "
+          env=${{ env.NETWORK }}
+          tags=@smoke
+          deployment=${{ env.DEPLOYMENT }}
+          platform=Linux
+          " > environment.properties
+  
+      - name: Send Results to Allure Server
+        uses: robkatona/send-allure-results@v1.0.5
+        if: ${{ always() }}
+        with:
+          allure-server-url: https://allure-server.prd.midnight.tools
+          allure-results-directory: ./typescript/packages/e2e-tests/allure-results
+          project-id: headless-wallet-${{ env.DEPLOYMENT }}
+          security-user: ${{ secrets.ALLURE_ADMIN_USER }}
+          security-pass: ${{ secrets.ALLURE_ADMIN_PASSWORD }}
+  
+      - name: Publish Jest E2E Test Report
+        uses: dorny/test-reporter@v1
         if: success() || failure()
         with:
-          name: scoverage-report
-          path: target/scala-3.4.2/scoverage-report
+          name: Jest E2E Tests Report
+          reporter: jest-junit
+          path: |
+            ./typescript/packages/e2e-tests/reports/report.xml
